
export const SIGN_IN = 'SIGN_IN'

export const SIGN_OUT = 'SIGN_OUT'

export const SIGN_UP = 'SIGN_UP'

export const INPUT_CHANGE = 'ADD_TEXT'

export const SUBMIT_QUESTION_SUCCESSFUL = 'SUBMIT_QUESTION_SUCCESSFUL'

export const SUBMIT_QUESTION_FAILED = 'SUBMIT_QUESTION_FAILED'
