
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL'

export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'

export const SIGN_OUT_SUCCESSFUL = 'SIGN_OUT_SUCCESSFUL'

export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED'

export const ADD_TEXT = 'ADD_TEXT'

export const SUBMIT_QUESTION_SUCCESSFUL = 'SUBMIT_QUESTION_SUCCESSFUL'

export const SUBMIT_QUESTION_FAILED = 'SUBMIT_QUESTION_FAILED'
