//POST AUTHENTICATION CREDENTIALS
export const SIGN_IN = 'SIGN_IN'

export const SIGN_IN_PENDING = 'SIGN_IN_PENDING'

export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED'

export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED'

//SIGN OUT
export const SIGN_OUT = 'SIGN_OUT'

export const SIGN_OUT_PENDING = 'SIGN_OUT_PENDING'

export const SIGN_OUT_FULFILLED = 'SIGN_OUT_FULFILLED'

export const SIGN_OUT_REJECTED = 'SIGN_OUT_REJECTED'